### ISSUE TITLE
New features require: add WebP & AVIF format support

### ISSUE THREAD

**Issue by liulifox233** [eesxy/ComicPacker#1]
需要更加现代化的文件格式支持，WebP 与 AVIF 的压缩效率比传统的 PNG 与 JPEG 高，可以有效减小打包体积，参见：[MDN Web Docs on Image Types](https://developer.mozilla.org/zh-CN/docs/Web/Media/Formats/Image_types)。

More modern file formats are needed. WebP and AVIF offer better compression efficiency than traditional PNG and JPEG, which can effectively reduce the package size. For more details, refer to: [MDN Web Docs on Image Types](https://developer.mozilla.org/zh-CN/docs/Web/Media/Formats/Image_types).

**Comment by eesxy** [comment]
感谢您的建议！已添加对WebP和AVIF的支持

**Comment by liulifox233** [comment]
非常感谢！
